const softwareData = [
    { name: "Windows 11", type: "System Software" },
    { name: "Microsoft Word", type: "Application Software" },
    { name: "Linux", type: "System Software" },
    { name: "Photoshop", type: "Application Software" },
    { name: "BIOS", type: "System Software" },
    { name: "macOS", type: "System Software" },
    { name: "Ubuntu", type: "System Software" },
    { name: "Google Chrome", type: "Application Software" },
    { name: "Firefox", type: "Application Software" },
    { name: "Visual Studio Code", type: "Application Software" },
    { name: "Excel", type: "Application Software" },
    { name: "PowerPoint", type: "Application Software" },
    { name: "Notepad++", type: "Application Software" },
    { name: "VLC Media Player", type: "Application Software" },
    { name: "Spotify", type: "Application Software" },
    { name: "Slack", type: "Application Software" },
    { name: "Zoom", type: "Application Software" },
    { name: "Adobe Illustrator", type: "Application Software" },
    { name: "Adobe Lightroom", type: "Application Software" },
    { name: "7-Zip", type: "Application Software" },
    { name: "WinRAR", type: "Application Software" },
    { name: "Docker", type: "Application Software" },
    { name: "Git", type: "Application Software" },
    { name: "Node.js", type: "Application Software" },
    { name: "MySQL", type: "Application Software" },
    { name: "PostgreSQL", type: "Application Software" },
    { name: "Oracle Database", type: "Application Software" },
    { name: "Android Studio", type: "Application Software" },
    { name: "Xcode", type: "Application Software" },
    { name: "IntelliJ IDEA", type: "Application Software" },
    { name: "Eclipse", type: "Application Software" },
    { name: "Chrome OS", type: "System Software" },
    { name: "Fedora", type: "System Software" },
    { name: "Debian", type: "System Software" },
    { name: "Windows Server 2019", type: "System Software" },
    { name: "Hyper-V", type: "System Software" },
    { name: "VMware Workstation", type: "Application Software" },
    { name: "TeamViewer", type: "Application Software" },
    { name: "AutoCAD", type: "Application Software" },
    { name: "MATLAB", type: "Application Software" },
    { name: "Blender", type: "Application Software" },
    { name: "OBS Studio", type: "Application Software" },
    { name: "Postman", type: "Application Software" },
    { name: "Adobe Acrobat", type: "Application Software" },
    { name: "Lightworks", type: "Application Software" },
    { name: "GIMP", type: "Application Software" },
    { name: "Krita", type: "Application Software" },
    { name: "Steam", type: "Application Software" },
    { name: "Epic Games Launcher", type: "Application Software" },
    { name: "MS-DOS", type: "System Software" },
    { name: "FreeBSD", type: "System Software" },
    { name: "Chrome DevTools", type: "Application Software" }
];
